---
- name: Provision image
  hosts: default
  become: true
  
  tasks:
    - name: Install tomcat
      package:
        name: 'tomcat'
        state: present
    
    - name: Install htop
      package:
        name: 'htop'
        state: present
